### ISSUE TITLE
Json error in latest experimental prevents the game from starting.

### ISSUE THREAD

**Issue by ifffrt** [LilShiningMan/LSM-Content-Pack#1]
Hey. Latest experimental of the game broke the mod somehow. Just a heads up.

**Comment by LilShiningMan** [comment]
Thanks for that. I'll take a look and hopefully get it fixed up soon.

**Comment by ifffrt** [comment]
Glad to hear. Btw the issue is largely with the removal of a few obsoleted items it seems https://github.com/CleverRaven/Cataclysm-DDA/pull/51309. I had a headache trying to fix one id in particular ("toolbox") which was not in the json. It turned out it was from Magiclysm mod or something.

**Comment by LilShiningMan** [comment]
It sounds like you're on top of it already, but I've updated the .zip.  I'm loading up error free now, so it should be good to go. If I missed something or you come across anything else, let me know! Thanks!

**Comment by ifffrt** [comment]
It's working great now! This issue can be closed now.
